name = input ('Hello! What is your name?')
print ('Welcome, '+name+'!')
a = int(input('Pick a length of your triangle: '))
print ('You picked '+str(a)+'.')
b = int(input('Pick another length for your triangle: '))
print ('You picked '+str(b)+'.')
print ('Let me find the hypotenuse of your right triangle...')
c = ((a**2)+(b**2))
print ('The length of the hypotenuse is '+str(c**(1/2))+'.')
